name: Check PR info

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  fail-if-PR-info-not-enough:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR not tag
        if: ${{ !(contains(github.event.pull_request.labels.*.name, 'major') || contains(github.event.pull_request.labels.*.name, 'minor') || contains(github.event.pull_request.labels.*.name, 'patch') || contains(github.event.pull_request.labels.*.name, 'skip')) }}
        run: |
          echo "請加上版本 Label"
          exit 1

      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ github.actor }}
